# Generated by Django 5.0.3 on 2024-05-07 18:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Service Type')),
                ('price', models.FloatField(verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
            },
        ),
        migrations.CreateModel(
            name='VehicleLicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Vehicle License Plate')),
            ],
            options={
                'verbose_name': 'Vehicle License Plate',
                'verbose_name_plural': 'Vehicle License Plates',
            },
        ),
        migrations.CreateModel(
            name='CarWashService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateTimeField(verbose_name='Service Date')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='Notes')),
                ('price', models.FloatField(verbose_name='Price')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registered by')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carwash.servicetype', verbose_name='Service Type')),
                ('vehicle_license_plate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carwash.vehiclelicenseplate', verbose_name='Vehicle License Plate')),
            ],
            options={
                'verbose_name': 'Car Wash Service',
                'verbose_name_plural': 'Car Washes Services',
                'indexes': [models.Index(fields=['service_date'], name='carwash_car_service_a6b891_idx')],
            },
        ),
    ]
